
name: Go

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker build
      uses: docker/setup-buildx-action@v2.7.0
      
    - name: Docker Login 
      uses: docker/login-action@v2.0.0 with
      with:
        username: marcones.ns
        registry: quay.io
        password: ${{ secrets.QUAY_PASSWORD }}
      
