
name: Go

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker build
      uses: docker/setup-buildx-action@v2.7.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: programa
      
    - name: Docker Login 
      uses: docker/login-action@v2.2.0
      with:
        username: marcones.ns
        registry: quay.io
        password: ${{ secrets.QUAY_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: marcones.ns/go_ci:${{github.ref_name}}
